name: Test Docker build for PR
on:
  pull_request:
    paths:
      - 'requirements.txt'
  workflow_dispatch: ~

jobs:
  build:
    name: Test Docker build for PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Test Docker build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=docker-release
