name: Publish Docker image
on:
  push:
    branches-ignore:
      - dependabot/**
    tags:
      - '**'
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.sample'

jobs:
  push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/rss-to-telegram
          flavor: latest=false
          tags: |
            type=ref,event=branch
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern={{major}}
            type=raw,value=latest,enable=${{ endsWith(github.ref, 'master') }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=docker-release
          cache-to: type=gha,scope=docker-release,mode=max
      - name: Set Docker meta (exp-deps)
        if: ${{ startsWith(github.ref, 'refs/heads') && github.ref_name != 'master' }}
        id: meta-exp
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/rss-to-telegram
          flavor: latest=false
          tags: type=raw,value=${{ github.ref_name != 'dev' && format('{0}-', github.ref_name) || '' }}exp-deps,enable=true
      - name: Push to Docker Hub (exp-deps)
        if: ${{ startsWith(github.ref, 'refs/heads') && github.ref_name != 'master' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          build-args: EXP_DEPS=1
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-exp.outputs.tags }}
          labels: ${{ steps.meta-exp.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta-exp.outputs.tags }}  # only one tag, safe to use
          cache-to: type=inline

  description:
    name: Update repository description on Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/rss-to-telegram
